### ISSUE TITLE
Research write-back cache enabling for Slot-2 external RAM

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#103]
Edge cases mostly involve cartridges which can do both external RAM and other features (most commonly, rumble); they should be considered before adding proper write-back cache enabling functionality.

**Comment by AntonioND** [comment]
To be fair, this is a corner case that almost nobody is ever going to hit. It's fine to investigate this, but I imagine that games will either use the RAM expansion or the rumble, but not both, as the number of cartridges that support both is very small.
