### ISSUE TITLE
.specs files missing in wonderful distribution

### ISSUE THREAD

**Issue by nbvdkamp** [blocksds/sdk#115]
After installing BlocksDS with `wf-pacman -S thirdparty-blocksds-git-toolchain` I got this error when building the latest version of the rom_combined template:
```
$ make
FIND: Parameter format not correct
  BIN2C.9 arm9/data/data_string.bin
arm-none-eabi-gcc: fatal error: cannot read spec file 'C:/msys64/opt/wonderful/thirdparty/blocksds/core/sys/crts/ds_arm9.specs': No such file or directory
compilation terminated.
make[1]: *** [build/arm9/arm9/data/data_string.bin.o] Error 1
make: *** [arm9] Error 2
```
I checked manually and they indeed seem to be missing:
![image](https://github.com/blocksds/sdk/assets/15140758/d356af4f-eda7-4958-933f-24f91cb23573)

Copying them to there from a clone of the repo fixed the problem.

**Comment by nbvdkamp** [comment]
Oh the examples and templates are downloaded with `thirdparty-blocksds-(git-)docs`, I see thank you.
Would be good to have that in the README

**Comment by AntonioND** [comment]
Yeah, that's fair enough, added: https://github.com/blocksds/sdk/commit/728db237d05b2daaa9a49e677dfb1b9b9f856d55
