### ISSUE TITLE
Camera example not working 

### ISSUE THREAD

**Issue by ablakely** [blocksds/sdk#117]
I'm having issues getting the camera example code working, the code launches but the DS just says 
```
   Camera Test
   Initializing camera...
```
on the bottom screen and the top screen is just blank

SDK version:
```
    $ cat /opt/blocksds/core/version.txt 
    f21add5e6abf3a286cbf14a98ebbaa2d68cd118c
```

it was installed using wf-pacman

**Comment by asiekierka** [comment]
Reproduced. There must be some kind of regression.

**Comment by asiekierka** [comment]
Oh, it's not a regression. It's much more silly.

**Comment by AntonioND** [comment]
This should be fixed now!
