### ISSUE TITLE
[ Enhancement ] Add support for TimeZones in FS operations

### ISSUE THREAD

**Issue by YourWishes** [blocksds/sdk#128]
Hello, please refer to this ongoing discussion;
https://github.com/DS-Homebrew/TWiLightMenu/issues/2360

Currently TWiLightMenu is using libfat for their FS operations, but are considering replacing with libnds FS operations. A current bug on the DSi firmware is a lack of TimeZone, and FS operations are assuming the time is set to UTC+0. This causes file timestamps to drift by the value of whatever the timezone the user is in, e.g. if I am in UTC+10:00 then when I save a file it will appear to have been saved 10 hours in the future from the actual time it was saved.

Just opening the conversation at this point, perhaps either extending rtcTimeAndDate struct or creating a new rtcTimeAndDateWithTimeZone struct could work instead. Alternatively adding some FILE operations that can take consideration of timezone(s), as I think this is one of the only affected areas.

Previously
https://github.com/blocksds/libnds/issues/87

**Comment by asiekierka** [comment]
Where would this timezone information be read from, and how would this be standardized across all homebrew?

I believe this is a bad idea - having 20% of homebrew write timestamps with UTC+10 and 80% with UTC+0 sounds intuitively worse than 100% writing timestamps with UTC+0.

**Comment by YourWishes** [comment]
OK sounds like it may be a non-starter, will take back to the TWiLight guys and see how best to tackle from that side. Main affected thing is NDS save files, so perhaps an extended file.h API with manual timezone as an argument would be best, but will wait and see what I can find on their side.

**Comment by AntonioND** [comment]
I'm not so worried about the lack of compatibility, I'm mostly worried about getting the timezone information to begin with. On DSi I guess you could get the firmware settings and guess the timezone from the country (but that's not reliable, the US has 4 timezones, Spain has 2 timezones, etc). And well, this would only work on DSi, not DS.

And I'm not sure about a manual argument. There are 3 protocols that DS homebrew support:
- DLDI: Most loaders do DLDI patching, this is very well supported in general.
- argv[]: This isn't well supported at all. A few flashcards support this right away, but it's a lot less common than DLDI.
- Reset to loader routine: This is barely ever supported.

I just think that a protocol to set the time zone simply wouldn't be adopted.

**Comment by AntonioND** [comment]
I'm going to close this, I think it's just too impractical for the reasons mentioned above by me and @asiekierka.
