### ISSUE TITLE
Add cooperative multithreading system

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#13]
We need a high level API that doesn't require users to allocate the stack and the coroutine contexts manually, something like this (open to ideas, discussion, etc):

```
typedef int (*coro_fn)(void *ctx, void *arg);

// Allocate memory for a coroutine and set up its context
int coro_create(int (*function)(void *ctx, void *arg), void *arg,
                size_t stack_size);

// Resume a coroutine from a different context
int coro_resume(int id);

// To be called from inside a coroutine
void coro_yield(void *ctx, int value);

// Returns 1 if the coroutine has ended
int coro_has_ended(int id);

// If the coroutine hasn't finished, it will resume it until it does.
// When it's finished, it will free the memory used by it and
// return its returned value.
int coro_join(int id);
```

We will also need mutexes at some point, but that can wait. The first PR should be a PR that adds the API to ``libsysnds`` and updates ``examples/coroutines`` to use the new API.

**Comment by AntonioND** [comment]
This is my first version of a cooperative multithreading scheduler:

https://github.com/blocksds/sdk/commit/fd68c3f1f03f357a7e3a9db54c565e78ea6d0369

https://github.com/blocksds/crts/commit/ddac6fc207735ea32e286b35abcdc2baa434e4b5

https://github.com/blocksds/libnds/commit/442a73aed1e4b6760cf83906417354fa3a12281e

Missing:
- Supporting different priority levels.
- Mutexes and things like that.

This doesn't affect any of the currently existing code. If the multithreading functions aren't used, the code behaves basically the same way it used to work before.

**Comment by AntonioND** [comment]
The current system is good enough to allow loading files from a secondary thread (which internally just waits for the ARM7 to load the data) while the main thread does other things:

https://github.com/blocksds/sdk/commit/3f0b7b1e1c9065ae68240c80cdb9672a4cb81bcd

**Comment by AntonioND** [comment]
I think that the only remaining task is to add a system of priorities.

**Comment by asiekierka** [comment]
What is missing for this, now that TLS is added?

**Comment by AntonioND** [comment]
I was thinking about priorities, but I'm not sure if it's worth the effort. I guess we can close this and create a new issue for that, if we decide it's useful.

**Comment by asiekierka** [comment]
It might be in light of https://github.com/blocksds/sdk/issues/61 .

**Comment by AntonioND** [comment]
I think we're getting to the point in which we need to consider if what we actually need is a pre-emptive multithreading system that can switch threads manually or when interrupts happen. However, libnds is not prepared for this.

**Comment by asiekierka** [comment]
With compiler TLS support, which we now have, I think it might not be too bad. However, that would be a new issue requiring its own analysis.

**Comment by AntonioND** [comment]
I'll close this for now as complete. We can open a new issue later.
