### ISSUE TITLE
libnds: Wrong comment on `keysDown()`

### ISSUE THREAD

**Issue by WiIIiam278** [blocksds/sdk#136]
Extremely minor, but something made me scratch my head for a few minutes: `uint32_t keysDown(void);` has the wrong comment, it seems :)

https://github.com/blocksds/libnds/blob/master/include/nds/arm9/input.h#L55-L58

should be "keys just pressed"...probably, right? :)

**Comment by AntonioND** [comment]
Thanks for noticing! Fixed in https://github.com/blocksds/libnds/commit/7b39e41871d9fee3d468f9d002bae4f537d94f7b
