### ISSUE TITLE
videoGL enum conversion issue breaks compilation of any C++ project

### ISSUE THREAD

**Issue by lifehackerhansol** [blocksds/sdk#140]
It seems at some point between v0.12 and v0.14 C++ compiling has been broken.

This can be tested directly from this repository by attempting to build `rom_arm9_only` with `main.c` renamed to `main.cpp`:
```
In file included from /opt/blocksds/core/libs/libnds/include/nds/arm9/boxtest.h:19,
                 from /opt/blocksds/core/libs/libnds/include/nds.h:136,
                 from source/main.cpp:8:
/opt/blocksds/core/libs/libnds/include/nds/arm9/videoGL.h: In function 'GL_TEXTURE_SIZE_ENUM glTexSizeToEnum(int)':
/opt/blocksds/core/libs/libnds/include/nds/arm9/videoGL.h:529:20: error: invalid conversion from 'int' to 'GL_TEXTURE_SIZE_ENUM' [-fpermissive]
  529 |             return -1;
      |                    ^~
      |                    |
      |                    int
 ```

**Comment by AntonioND** [comment]
That was reported some days ago, and it's fixed here: https://github.com/blocksds/libnds/commit/069dd18d15e7b8af2e8555d47c08b3c0f9484a1b

There should be a new release this weekend to fix that. Until then I believe that the git package in Wonderful Toolchain should have the fix.

**Comment by lifehackerhansol** [comment]
I see, I'll just use the git package in the meantime.
