### ISSUE TITLE
Background-related documentation issues

### ISSUE THREAD

**Issue by NovaSquirrel** [blocksds/sdk#143]
Here are issues I ran into when working with the functions in https://blocksds.github.io/docs/libnds/group__background__api__group.html:

`bgScroll()` mentions that the fractional part is ignored, but the function that takes a fixed point number is actually `bgScrollf()`. It would also be nice if it mentioned `bgUpdate()`

`bgSetPriority()` says `Higher level priority will result in background rendering on top of lower level priority.` but I think it needs the additional context that lower numbers are higher priority and higher numbers are lower priority. The sprite documentation does explain this.

**Comment by AntonioND** [comment]
> `bgScroll()` mentions that the fractional part is ignored, but the function that takes a fixed point number is actually `bgScrollf()`. It would also be nice if it mentioned `bgUpdate()`

I don't see any mention that the fractional part is ignored, can you check that again? I'm not sure about mentioning `bgUpdate()`, that function needs to be called after doing anything with the background functions, basically, so I would have to mention it everywhere.

> `bgSetPriority()` says `Higher level priority will result in background rendering on top of lower level priority.` but I think it needs the additional context that lower numbers are higher priority and higher numbers are lower priority. The sprite documentation does explain this.

Yeah, that's true, fixed! https://github.com/blocksds/libnds/commit/e81a34445a723703454c4dbe8bedc43349b9068b

**Comment by NovaSquirrel** [comment]
> I don't see any mention that the fractional part is ignored, can you check that again?

On https://blocksds.github.io/docs/libnds/group__background__api__group.html#gacde59e425f91c5c2987f5a2cef94b947 there is currently this note on `bgScroll()`

![image](https://github.com/blocksds/sdk/assets/1865623/fa79279d-472a-4708-9ac6-5ec6fa41bc0b)

**Comment by AntonioND** [comment]
Ah, fair, I see what you mean. I've removed that note from `bgScroll()`. https://github.com/blocksds/libnds/commit/d7db4756c1d60ca6c5ab92b4989b27a4579cad80
