### ISSUE TITLE
docs: Document ways of debugging homebrew.

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#154]
In roughly this order:

* NO$GBA console output
* `-lnds9d`/`-lnds7d`
* `sassert()`
* melonDS GDB server
* NO$GBA debugger

**Comment by AntonioND** [comment]
I've added a new page about this:

https://github.com/blocksds/sdk/commit/6e9dd25b12dd54c85607dd35843ee6eac0afc913

https://blocksds.github.io/docs/usage/debugging/

This is still missing a section about how to use GDB to debug with melonDS.

**Comment by AntonioND** [comment]
I've also made `assert()` work on both the ARM9 and ARM7 work: https://github.com/blocksds/libnds/commit/bf3ef5be198a7e9e1c084ed5e4ace4307cb8a6e2

**Comment by AntonioND** [comment]
We need to mention the stack protector too.

**Comment by AntonioND** [comment]
And this adds the last section, GDB with melonDS I haven't bene able to get it to work, I will try again later, but this is the general idea: https://github.com/blocksds/sdk/commit/d0974d093cad023a111b5949c37779d3c0a56cf3

**Comment by AntonioND** [comment]
I've also tried GDB debugging with DeSmuME, and that works: https://github.com/blocksds/sdk/commit/2978d5f39ef0c123e1931c9d82330931cfa3cc68
