### ISSUE TITLE
Proposal: Zig Toolchain Option

### ISSUE THREAD

**Issue by GalaxyShard** [blocksds/sdk#176]
[Zig](https://ziglang.org/) provides a great toolchain for compiling C/C++/Zig projects. I believe BlocksDS could benefit from using Zig's toolchain for the following reasons:

1. Cross compilation is first-class and works out-of-the-box for all supported platforms without downloading anything extra. This should automatically add MacOS/FreeBSD support to the SDK

2. Very simple installation, available on package managers for Linux, Windows, MacOS, FreeBSD..., works on many architectures, provides builds for x86-64, x86, aarch64, arm, riscv64, powerpc64le

3. Entire toolchain is self-contained making installations easily manageable; there is no need to set up symbolic links, deal with various forks of pacman, configure environment variables, etc.

I have been working on making libnds compile with Zig [in this repository](https://github.com/GalaxyShard/zig-nds) although there are still a few assembler errors from LLVM.

**Comment by asiekierka** [comment]
Note the following, however:

1. Porting BlocksDS to a given platform requires also porting all of its tools; while we have minimized the amount of third-party dependencies required, it may still be a bit of a hassle.

2. Porting BlocksDS to a given platform also requires using and linking with `picolibc` specifically; we rely on its approach to system calls in many ways. For an LLVM-centric environment, I would probably recommend linking it with Clang `libc++`,  as the `libstdc++` license reverts to the GPLv3 if not used with GCC specifically - this requires a rebuild.

3. LLVM-generated code is currently noticeably (though the exact percentage varies heavily) slower than GCC-generated code on ARMv4/ARMv5-class machines; there are [some open issues (non-exhaustive)](https://github.com/llvm/llvm-project/issues?q=is%3Aopen+label%3Abackend%3AARM+author%3Afelixjones) which would improve the situation, but there's naturally little interest from Arm itself to look into them.

We have nothing against other projects using our BlocksDS work, but for these reasons it is unlikely to become the official solution in the short term.

**Comment by AntonioND** [comment]
I was going to mention the performance difference between GCC and LLVM, but asie has already done it.

Apart from that, I'll just say that, by checking your repository, you're basically rewriting all the library headers in Zig. This is a lot of effort, and we barely even have time to maintain the C libraries. If anything, we could consider C++ in the future, when we have full WiFi support and things like that, but Zig is a completely different story.

We aren't against people using BlocksDS their own way. If you want to get the library archives that we distribute, package them with a Zig toolchain, and distribute that, it's fine. But your idea makes more sense as an independent project.

If we accepted Zig, someone would come suggesting Nim, someone else would come with C++, and why not Lua? You get the idea. Our main goal is to support all of the hardware of the NDS, document it, and make it relatively user-friendly, and we're still far away from that.

If you really decide to work on this, my advice is to stick to tagged versions, of course. Don't try to follow the current state of the repository, but the last tagged version of the repository.

**Comment by GalaxyShard** [comment]
> Apart from that, I'll just say that, by checking your repository, you're basically rewriting all the library headers in Zig. This is a lot of effort, and we barely even have time to maintain the C libraries. If anything, we could consider C++ in the future, when we have full WiFi support and things like that, but Zig is a completely different story.

I should have specified--this is because I am also writing some convenience bindings to libnds for a project of my own. Porting over the headers is not necessary to use the Zig toolchain, the only files that would be upstreamed from that repo (if this proposal were to be accepted) are build.zig.zon and build.zig.

> If we accepted Zig, someone would come suggesting Nim, someone else would come with C++, and why not Lua? You get the idea. Our main goal is to support all of the hardware of the NDS, document it, and make it relatively user-friendly, and we're still far away from that.

To be clear I am only suggesting the toolchain/build system as an alternative to the current Makefiles and Wonderful Toolchain, not Zig as a second programming language alongside C. I think this could aid in making the toolchain more user friendly and quicker to set up, since it's a one-liner to get it from any package manager.

> If you really decide to work on this, my advice is to stick to tagged versions, of course. Don't try to follow the current state of the repository, but the last tagged version of the repository.

I'll keep this in mind, thank you.

**Comment by asiekierka** [comment]
>I think this could aid in making the toolchain more user friendly and quicker to set up, since it's a one-liner to get it from any package manager.

Yes, but can that cover the tools that we rely on: `bin2c`, `grit`, `mmutil`, `ndstool`, `squeezer`, etc.? `ndstool` is required for all builds, while at least one of the other four is required for any project of non-trivial complexity. I suspect that the solution here would require learning Zig to write build scripts by end users, which may not necessarily be a trivial affair compared to editing a rules-based Makefile (but I haven't looked into it much).

While I'm interested in Zig myself, I don't see it as a viable replacement of the current packaging method as such - an alternate programming language usable with the existing toolchain, sure. In addition, as we don't have the resources and value a consistent build environment for things like end user issue triage, I don't see us maintaining two incompatible ways to install two different toolchains that can be used with BlocksDS.

**Comment by AntonioND** [comment]
I'm closing this as not planned.
