### ISSUE TITLE
Compatibility with LLVM

### ISSUE THREAD

**Issue by GalaxyShard** [blocksds/sdk#184]
Related: #176

This would help with my project getting BlocksDS to build entirely with Zig. LLVM already provides strong compatibility with GCC using `-std=gnu17`, so it should require minimal changes to fix errors/warnings when compiling with LLVM. I'd be happy to make a pull request.

**Comment by asiekierka** [comment]
I see no problem with a pull request being made for this purpose.

I've reviewed your changes so far briefly, and the `tmio.twl.c` compliance improvements look OK, whereas for renaming `.s` files to `.S` I'd try to find an LLVM/Clang-side option that works similarly to `-x assembler-with-cpp` instead; while this is not compliant with the GCC standards, many parts of the homebrew community do indeed assume lower-case `.s` files to include the C preprocessor.

**Comment by AntonioND** [comment]
Also, relying on the case of a file extension is going to cause issues if you're using Windows. I suppose that's why the homebrew community has always ignored that GCC rule.

**Comment by profi200** [comment]
Regarding my TMIO driver i feel like we had this one before and the atomic type thing was solved. At least i did solve it in my variant for the 3DS.

**Comment by GalaxyShard** [comment]
Think it would be reasonable to keep both `-x assembler-with-cpp` for windows & backwards compatibility and also change the file extensions to use a capital S following the standard? LLVM does implement assembler-with-cpp so it's not strictly necessary either way.

**Comment by GalaxyShard** [comment]
Currently the only compilation issue in libnds is include/nds/bios.h, seemingly due to LLVM not considering `(1f - .)` (should be 2 in Thumb mode, 4 in Arm if I understand correctly) to be an immediate value in inline assembly. I could get rid of the whole `<< ((1f - . == 4) * -16); 1:` part of each `swi`, but then I imagine it would compile incorrectly in Arm mode. Any ideas?

This is one of the lines:
```c
asm volatile inline ("swi 0x3 << ((1f - . == 4) * -16); 1:" : "+r"(r0) :: "r1", "r3");
```
Error:
```c
projects/libnds-fork/include/nds/bios.h:123:26: error: operand must be an immediate in the range [0,255]
    asm volatile inline ("swi 0x3 << ((1f - . == 4) * -16); 1:" : "+r"(r0) :: "r1", "r3");
```

**Comment by asiekierka** [comment]
I've ran into the same issue with Clang, and it feels like it might be an LLVM limitation.

The only idea I have is to essentially revert https://github.com/blocksds/libnds/commit/23a669f4706e35a11f5d46ac08edac21d226401d - this should be fairly easy as we kept the non-inline implementations in the code, just culled them from the header; you'd have to do something like this:

```diff
@@ -136,6 +152,9 @@ static inline int swiRemainder(int numerator, int divisor)
 /// @param divisor Signed integer to divide by.
 /// @param result Pointer to integer set to numerator / divisor.
 /// @param remainder Pointer to integer set to numerator % divisor.
+#ifdef __clang__
+void swiDivMod(int numerator, int divisor, int *result, int *remainder);
+#else
 __attribute__((always_inline))
 static inline void swiDivMod(int numerator, int divisor, int *result, int *remainder)
 {
@@ -145,6 +164,7 @@ static inline void swiDivMod(int numerator, int divisor, int *result, int *remai
     *result = r0;
     *remainder = r1;
 }
+#endif

 /// Copy in chunks of halfword size.
 #define COPY_MODE_HWORD        (0)
 ```

**Comment by AntonioND** [comment]
Is there anything left to do for this?

**Comment by AntonioND** [comment]
I assume this is now completed, so I'm closing it.
