### ISSUE TITLE
no source in tools/

### ISSUE THREAD

**Issue by PypeBros** [blocksds/sdk#187]
- pulled 5e58beb17d45d57f08c
- tried to run `make` at the root
- build failed in `tools/dldipatch` saying "no targets specified and no makefile found"
- directory appears to be empty.
- same for the `ndstool`, `grit`, `mmutil` and `squeezer` directories

**Comment by PypeBros** [comment]
nevermind ... I missed the `git submodule init ; git submodule update` part.

**Comment by AntonioND** [comment]
Yeah, the documentation mentions it (step 4), sorry if it wasn't obvious: https://blocksds.github.io/docs/setup/options/from_source/
