### ISSUE TITLE
Compress ``default_font.bin``

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#2]
In libnds, the default font is very big and it isn't compressed: ``source/arm9/default_font.bin``

It is needed to tell grit to compress it by modifying the ``.grit`` file, and to modify the code that loads it to decompress it.

**Comment by asiekierka** [comment]
No longer necessary. `default_font.bin` has gone from 8KB to 760 bytes; at that point, the overhead of adding decompression code to `console.c` and the decompression header would probably match or outweigh any gains, in addition to the notes you've made about minimizing reliance on SWI BIOS functions for a panic handler.
