### ISSUE TITLE
NitroFS: Ignore direct Slot-2 access if ROM header marked as >32MB

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#200]
Allegedly, NO$GBA mounts a `.nds` file to both Slot-1 and Slot-2, but Slot-2 access is limited to the first 32 MB, leading to corruption when accessing NitroFS files past that limit. Even if it doesn't, this patch is a good idea for potentially catching some very broken pre-DLDI Slot-2 `.nds` loaders, if they ever existed.

**Comment by asiekierka** [comment]
https://github.com/blocksds/libnds/pull/126

**Comment by AntonioND** [comment]
Yep, I've reproduced the bug locally with no$gba. Unexpected! Thanks for the fix!
