### ISSUE TITLE
`nocashWrite` strips newlines for melonDS and DeSMuME

### ISSUE THREAD

**Issue by jonko0493** [blocksds/sdk#203]
In commit https://github.com/blocksds/libnds/commit/cba49ffdbbe6da84f98b3688f887edcff19da453:

> Every time that nocashWrite() is called, no$gba adds a newline character after the string.

It's true that no$gba does this, but melonDS and DeSMuME do not. Because the current implementation relies on no$ to auto-insert newlines, the other two emulators just get their debug messages all smashed together.

Imo, the solution here is to append a newline to the nocash buffer. In no$gba itself this will result in double newlines for each entry, but I personally think this is a fine trade off and doesn't reduce usability substantially in the way not having newlines in the other emulator consoles does.

Sample as seen in the DeSMuME console:
![image](https://github.com/user-attachments/assets/ac575fbe-d486-4fc9-aae3-2be55f835e12)

**Comment by AntonioND** [comment]
melonDS now should do this, but you aren't building it from source, which includes this commit: https://github.com/melonDS-emu/melonDS/pull/2119

**Comment by jonko0493** [comment]
Valid and fair enough; if it's fixed upstream in melonDS I don't have an issue. Closing.

**Comment by AntonioND** [comment]
What I didn't know is that desmume also supports this way to print debug messages, it may be a good idea to uniformize the behaviour there as well.
