### ISSUE TITLE
Add support for the "retail" DS Motion Pack

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#216]
https://github.com/melonDS-emu/melonDS/issues/74

According to @xperia64, the Motion Pack bundled with Tony Hawk Motion uses the same accelerometer, but a different data reading path.

**Comment by AntonioND** [comment]
Well, it would be nice to support it for sure, but I guess this requires a slot-2 flashcart to run the NDS ROM, or a DSi so that the NDS ROM can run from the SD card, right?

**Comment by asiekierka** [comment]
> but I guess this requires a slot-2 flashcart to run the NDS ROM, or a DSi so that the NDS ROM can run from the SD card, right?

It's a Slot-2 addon. We already support the homebrew variant ("DS Motion Pak"), but not the one bundled with Tony Hawk's Motion - which has the same chip, but a different communication protocol.
