### ISSUE TITLE
Use UAL syntax for assembly (in Maxmod)

### ISSUE THREAD

**Issue by GalaxyShard** [blocksds/sdk#226]
A few reasons:

- UAL syntax supersedes the former syntax according to ARM ([documentation](https://developer.arm.com/documentation/dui0473/m/writing-arm-assembly-language/about-the-unified-assembler-language))
- LLVM's assembler (intentionally) does not support pre-UAL ARM syntax, preventing compilation of anything that relies on the particular syntax quirks of pre-UAL syntax ([issue, closed with wontfix](https://github.com/llvm/llvm-project/issues/23881))
- UAL ARM assembly should be able to be compiled for the ARM7 and ARM9 without changes, and in both thumb/arm mode as well. Might be relevant for building from source, and switching between ARM/thumb.
- According to comments in the LLVM issue, it has been the standard syntax for quite a long time (2003 or so?)

This is particularly relevant for Maxmod since it is implemented in assembly.

**Comment by asiekierka** [comment]
Most of the toolchain (libnds, dswifi) has used unified syntax for years; do you mean specifically maxmod?

**Comment by GalaxyShard** [comment]
It's mostly relevant for maxmod; I hadn't noticed that libnds was already using it. I ran a `grep` for `.syntax` and found that these assembly files don't contain `.syntax unified`:
```
in ndstool:
    ./misc/loadme.s
in libteak
    ./source/crt0.s
    ./source/cpu_asm.s
    ./asm/crt0.s
    ./asm/cpu_asm.s
in libnds:
    ./source/arm9/teak/utils.twl.s
in maxmod:
    ./source_ds7/mm_sleep.s
    ./source_ds7/mm_mixer_super.s
    ./source_ds7/mm_reverb.s
    ./source_ds7/mm_comms7.s
    ./source/mm_effect.s
    ./source/mm_mas_arm.s
    ./source/mm_main.s
    ./source/mm_mas.s
    ./source_ds/mm_stream.s
    ./source_gba/mm_init_default.s
    ./source_gba/mm_mixer_gba.s
    ./source_ds9/mm_memory.s
    ./source_ds9/mm_main9.s
    ./source_ds9/mm_comms.s
    ./source_ds9/mm_soundbank.s
    ./source_ds9/mm_flusher.s
```

**Comment by asiekierka** [comment]
The `ndstool` one is not used in the build process, it's just for preservation purposes.

The `libnds` one is simple enough that it should compile on UAL too, but it's correct that it's not marked as UAL when it should be.

This leaves `libteak` and `maxmod`.

**Comment by AntonioND** [comment]
I guess with the two PRs merged this issue can be closed, thanks both!

**Comment by asiekierka** [comment]
Did we ever fix `libteak`? I only fixed `libnds`'s `teak` - slightly different.
