### ISSUE TITLE
`ndstool -n` is a no-op

### ISSUE THREAD

**Issue by lifehackerhansol** [blocksds/sdk#240]
The `-n` flag, as written in the help message:
```
 Latency              -n [L1] [L2]                   default=maximum
```

These pass `latency1` and `latency2` respectively, and is meant to be applied here: https://github.com/blocksds/ndstool/blob/master/source/ndscreate.cpp#L366-L367

which should result in changed values at 0x60 and 0x64 of the header.

However, ndstool further down that function hardcodes its own values: https://github.com/blocksds/ndstool/blob/master/source/ndscreate.cpp#L724-L725

This means that passing this flag does nothing at all.

**Comment by asiekierka** [comment]
https://github.com/blocksds/ndstool/pull/11

**Comment by AntonioND** [comment]
Thank you both for the report and fix!
