### ISSUE TITLE
Loading the libnds keyboard now sets the background color to magenta

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#28]
Since this PR has been merged, loading the keyboard at the same time as the default console turns the console magenta: https://github.com/blocksds/libnds/pull/5

This can easily be seen in either of the templates (ARM9-only or combined).

**Comment by AntonioND** [comment]
@asiekierka

**Comment by asiekierka** [comment]
https://github.com/blocksds/libnds/pull/12

**Comment by AntonioND** [comment]
Merged, thanks for the fix!
