### ISSUE TITLE
Support animated icons in ndstool

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#31]
https://problemkaputt.de/gbatek.htm#dscartridgeicontitle

**Comment by asiekierka** [comment]
Technically, ndstool supports adding a raw banner/icon .bin file, so this could also be a separate tool. (Which might be a good idea, as some additional flexibility is warranted - there's only 8 images and 8 palettes supported, but many more frames, for example.)

**Comment by AntonioND** [comment]
https://github.com/TheGameratorT/NDS_Banner_Editor

**Comment by AntonioND** [comment]
https://gist.github.com/Epicpkmn11/232b7568eed650e11523da4b01c7f64f

**Comment by asiekierka** [comment]
https://github.com/blocksds/ndstool/pull/5

**Comment by AntonioND** [comment]
Fixed in https://github.com/blocksds/ndstool/pull/5
