### ISSUE TITLE
Support DSi-exclusive ROMs

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#32]
Right now, the current crt0 and linkerscript support DSi-compatible applications.

We probably want to create a new crt0 and linkerscript for DSi-exclusive applications so that they can take advantage of all the additional RAM.

**Comment by asiekierka** [comment]
Without using the .twl code space*

**Comment by AntonioND** [comment]
I've been thinking about this, and I'm not sure we can do this safely.

Any DSi-only ROM will need to check that it's actually running in DSi mode (right at the start of the program). Then, you can use that check to show an error screen to the user like the ones you got with GBC-exclusive games when running on a GB ("This game has been designed for the Nintendo Game Boy Color").

If we only have one big RAM area, how can you load the initial code that checks for the DSi mode, and shows that error screen?

I'm inclined to close this issue and forget about this idea.

**Comment by asiekierka** [comment]
>If we only have one big RAM area, how can you load the initial code that checks for the DSi mode, and shows that error screen?

Proposal: No error screen; add a blob of code to crt0 which returns to loader (or powers off the console) if not. The NDS/DSi cartridge header should already state if a program is DSi-exclusive or not, so a well-behaved loader should refuse to run DSi-exclusive homebrew applications in NDS mode.

I'm not sure how complex that would be to achieve in practice, though.

**Comment by AntonioND** [comment]
Returning to the loader or powering off the console would only make users worry that the game is doing something dangerous, I think, and anything that involves modifying loaders is a lost cause. The loaders that are still being developed are for DSi, where the DSi-only check doesn't make sense, and then there is nds-hb-menu, which probably won't add that check because devkitARM doesn't support building DSi-only ROMs. Most other loaders are probably set in stone forever.

In any case, this reminds me of GBC/GB because in there the GBC cartridges were physically modified to not fit in a GB, so it's technically impossible for that error to show to a normal user, but they still check if they have started in GB or GBC mode.

**Comment by asiekierka** [comment]
Coming back to this issue, I don't think there's much point in doing this at the toolchain level:

* The NTR-specific support code is fairly small, while adding a way to remove it would further complicate the linking process.
* The ARM9/ARM7 binary size restrictions apply regardless, so you still have to move a bunch of code/data to `.twl` or load things in via NitroFS.

All in all, I think the drawbacks are higher than the benefits of supporting this at the toolchain level, and homebrew can simply check `isDSiMode()` if they don't support DS consoles.

**Comment by AntonioND** [comment]
Yeah, I agree, I think we can close this.
