### ISSUE TITLE
Include gba-jpeg-decode as an optional library

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#33]
http://members.iinet.net.au/~freeaxs/gbacomp/#Displaying%20a%20JPEG%20Image%20on%20the%20GBA

EDIT: The link is down, this is an archived copy: https://web.archive.org/web/20230130121359/http://members.iinet.net.au/~freeaxs/gbacomp/#Displaying%20a%20JPEG%20Image%20on%20the%20GBA

**Comment by AntonioND** [comment]
Note that the code doesn't have a license, so it is required to get permission from the author to change the license (to Zlib, if possible, to make things easier).

**Comment by asiekierka** [comment]
Given that we now have an institution of external/third-party libraries (with some already in the wild, such as Nitro Engine and NFlib), I'd say this can be closed and made to no longer be a BlocksDS issue per se.

**Comment by AntonioND** [comment]
I've decided to play a bit today to relax from the DSP and the filesystem: https://github.com/blocksds/gbajpeg

**Comment by AntonioND** [comment]
I've added a link to the repository here: https://github.com/blocksds/sdk/commit/a793bb535ea4b562f3e159d3c3f463057719afd4
