### ISSUE TITLE
Integrate libxm7 as an additional music player

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#34]
https://github.com/sverx/libxm7

https://web.archive.org/web/20190122024428/wcms.teleion.it/users/cgq/nds/libxm7/

**Comment by AntonioND** [comment]
Integrated: https://github.com/blocksds/libxm7/tree/2e3f34dd4f52b85c4171be62c7d6a37b24a05ee6

Example: https://github.com/blocksds/sdk/tree/942af3ce30dabcdf359b607b6aadbf84a9fd1205/examples/libxm7

Thanks for your work, @sverx.

**Comment by sverx** [comment]
This is the most recent snapshot available of the original website:
https://web.archive.org/web/20210331025909/http://www.teleion.it/users/cgq/nds/libxm7/

:wave:

**Comment by AntonioND** [comment]
I've just checked, and the text of the version I used is the same, so nothing more to do. :)
