### ISSUE TITLE
Investigate error with PATH_MAX

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#35]
https://github.com/blocksds/libnds/blob/c42be06042812e5aec918c479f5a9919ce435897/source/arm9/libc/chdir.c#L13-L15

For some reason, ``limits.h`` isn't including this definition.

**Comment by asiekierka** [comment]
Fixed in `12.2.0-2` packages on my side.

**Comment by AntonioND** [comment]
Yup, that seems to have worked: https://github.com/blocksds/libnds/commit/ea8b2a4ff0642ff0eea86edc219d6e1a9ddc47b5
