### ISSUE TITLE
bin2c unexpectedly generates filenames with underscores

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#52]
```
  BIN2C.9 arm9/data/04.pal.bin
cc1: fatal error: build/arm9/arm9/data/04.pal_bin.c: No such file or directory
```

A file `04_pal_bin.c` gets created by `bin2c`, while the `Makefile` expects `04.pal_bin.c`. This should be fixed to be consistent - one way, or the other.

**Comment by AntonioND** [comment]
It looks like the makefiles of devkitpro projects are also broken, actually:

https://github.com/devkitPro/devkitarm-rules/blob/f7ff8e88d3bff66335da08a6e3d8f175e5ab5f69/base_tools#L50-L52

```
bin2s -a 4 -H `(echo $(<F) | tr . _)`.h $< | $(AS) -o $(<F).o
```

This turns "my.bin.bin" into "my_bin_bin.h". However, the makefile expects "my.bin_bin.h":

https://github.com/devkitPro/nds-examples/blob/6afa09b2054c9f47685514c32873b3905721c9ee/Graphics/3D/Display_List_2/Makefile#L192-L196

**Comment by AntonioND** [comment]
Can you test with this PR and see if it works? https://github.com/blocksds/sdk/pull/53

**Comment by asiekierka** [comment]
Seems to work fine now:

```
  BIN2C.9 arm9/data/04.pal.bin
test
  BIN2C.9 arm9/data/04.img.bin
test
  BIN2C.9 arm9/data/nitrotracker_logo_pal.bin
test
  BIN2C.9 arm9/data/nitrotracker_logo.bin
test
```

**Comment by AntonioND** [comment]
Oops, forgot to remove the "test" `printf()`. Removed, and PR merged. https://github.com/blocksds/sdk/commit/876b6415a332ea879c7b7ed92c8ae3b6f0cbe27d
