### ISSUE TITLE
Template ROM Keyboard missing sanitization

### ISSUE THREAD

**Issue by Lorenzooone** [blocksds/sdk#54]
Pressing backspace when there is nothing written with the keyboard in the "combined ROM", leads to jank.
Pressing Enter when there is nothing written also leads to jank. Less janky, but still janky.

**Comment by asiekierka** [comment]
Alternate solution: https://github.com/blocksds/libnds/pull/29 , which fixes the keyboard issues; then the above commit could probably be reverted.

**Comment by AntonioND** [comment]
I've merged that PR, and partially reverted that commit (I've kept the individual examples, without the big warning about `scanf`): https://github.com/blocksds/sdk/commit/3525a15eae7f155d0b4fc11402c3d135cd5c56ed
