### ISSUE TITLE
dswifi allocates >60KB RAM just by being compiled in

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#56]
```
0203c320 g     O .bss   00009f44 Wifi_Data_Struct 
020463f8 g     O .bss   00005240 dnsrecords 
0204be98 g     O .bss   00000400 ArpRecords 
```
These stand out; they can certainly be slimmed down, or made dynamically allocated.

**Comment by brais-sg** [comment]
Also, on the ARM7 side [maybe some memory](https://github.com/blocksds/dswifi/blob/master/source/arm7/wifi_arm7.c#L22) can be allocated dinamically?

**Comment by asiekierka** [comment]
ARM7 code is only designed for static allocation for the time being.
