### ISSUE TITLE
Support ``fopencookie()``

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#57]
This would let developers use their own filesystems with the ``stdio.h`` functions, in a more standard way than ``devoptab``. The only issue is that it's limited to file accesses:

https://linux.die.net/man/3/fopencookie

asie's suggestion is to use the top 4 bits of the file handler to encode the filesystem type, because the address space of the DS doesn't get that far.

Also, it may be a good idea to send a PR to ``picolibc`` if the code can be reused by other projects.

**Comment by asiekierka** [comment]
picolibc provides the (admittedly less intuitive) `fdev_setup_stream` and `fdevopen` macros/functions as a starting point.

**Comment by asiekierka** [comment]
picolibc is about to implement `funopen()`, which serves an identical purpose (but is a BSD-ism rather than a glibc-ism): https://github.com/picolibc/picolibc/pull/731

**Comment by AntonioND** [comment]
I think we can close this issue. Whenever picolibc supports `funopen()` we will get it for free. The whole point of opening the issue in this repository was that we didn't think it was going to be supported upstream.

**Comment by asiekierka** [comment]
picolibc has just merged it. I will provide an updated build in time for BlocksDS 1.3.0.
