### ISSUE TITLE
DLDI templates

### ISSUE THREAD

**Issue by lifehackerhansol** [blocksds/sdk#58]
It would be nice to see if it is possible to compile DLDI drivers under BlocksDS, as well as an example for future porting.

devkitPro's example DLDI is here: https://github.com/devkitPro/nds-examples/tree/master/templates/dldi

And a myriad of DLDI source codes can be found here: https://github.com/DS-Homebrew/DLDI

In terms of linking, we already have `dldi.ld` forked to BlocksDS. So it wouldn't be _too_ awful to craft a Makefile for the purpose, but I have no idea how to write a proper makefile :sweat_smile:

**Comment by AntonioND** [comment]
https://github.com/blocksds/sdk/tree/master/templates/dldi

This should be enough. I've also added the option to build it for the ARM9 or ARM7. In case it's built for the ARM7, the ``FEATURE_ARM7_CAPABLE`` flag is set as well.

I haven't tested it, though.

**Comment by lifehackerhansol** [comment]
The logic here appears to be flipped, it is using DARM7 when DLDI_ARM9=1.

https://github.com/blocksds/sdk/blob/13c6c0b908cf8d3d0c1df0dc1812a88ad8a8ceed/templates/dldi/Makefile#L79-L85

**Comment by lifehackerhansol** [comment]
This also needs to be in one line, or AS throws a compilation error: https://github.com/blocksds/sdk/blob/13c6c0b908cf8d3d0c1df0dc1812a88ad8a8ceed/templates/dldi/source/dldi_stub.s#L45-L46

(below file lines are different as this is my own DLDI's port)
```
source/dldi_header.s: Assembler messages:
source/dldi_header.s:50: Warning: missing operand; zero assumed
source/dldi_header.s:51: Error: junk at end of line, first unrecognized character is `0'
make: *** [Makefile:166: build//source/dldi_header.s.o] Error 1
```

**Comment by lifehackerhansol** [comment]
I've fixed the above issues in #65.

**Comment by AntonioND** [comment]
Merged! Is this all? If so, this issue can be closed.

**Comment by lifehackerhansol** [comment]
Yes, works otherwise. Thank you!
