### ISSUE TITLE
DSi Teak DSP support

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#60]
This is one of the two tough omissions from the DSi support of BlocksDS left, now that the camera is supported.

### Documentation

 - [GBAtek](https://problemkaputt.de/gbatek.htm) has most of what you need.
 - The [unofficial GBAtek addendum](https://melonds.kuribo64.net/board/thread.php?id=13) has some corrections.
 - The [teakra](https://github.com/wwylele/teakra) source code tree includes some snippets of documentation of its own.

### Prior art

- [teakra](https://github.com/wwylele/teakra) by wwylele is an emulator, assembler and disassembler for the Teak DSP architecture.
- [teak-llvm](https://github.com/Gericom/teak-llvm) by Gericom is a janky-but-serviceable port of LLVM and Clang to the Teak architecture. It is already packaged as part of the Wonderful toolchain repository (`wf-pacman -S toolchain-llvm-teak`).
- [The dsp-audio branch of GBARunner2](https://github.com/Gericom/GBARunner2/tree/feature/dsp-audio) by Gericom is perhaps the only currently published implementation of a custom DSP program, as well as of a production-grade application making use of the DSP.
- [DSiDsp](https://github.com/Gericom/DSiDsp/) is an example of a codebase which talks to and loads a Nintendo-provided AAC decoder for the Teak.

### Challenges/Notes

- teak-llvm is rather janky, in no small part due to the very limited userbase (of one), as well as some quirks of the Teak architecture (like 16-bit word-based memory addressing).
- The ticket probably has to be split into multiple parts, at least two:
  1. Adding support for communicating with the DSP, as well as loading DSP binaries (either DSP1 or a custom format) to libnds. (Could be split further into multiple parts: register definitions, then communication functions, then a binary loader)
  2. Writing a basic toolset for building DSP binaries ("Hello, world!"-style example/test, Makefile, linker), probably based around teak-llvm.
- Note that writing a DSP toolchain may also be of interest to the 3DS homebrew community.

**Comment by AntonioND** [comment]
The following 2 PRs add basic DSi support:
- https://github.com/blocksds/sdk/pull/91
- https://github.com/blocksds/libnds/pull/40

This is still very much a work in progress, but it's good enough to think about integrating it with the SDK, I believe.

**Comment by asiekierka** [comment]
Yes, I would say the scope of these PRs are good enough for integrating them with the SDK, though not necessarily to push a new release with "DSP support" as a headline item :-)

I've left some comments.

**Comment by AntonioND** [comment]
Thanks for the review! After merging the PRs, the current situation is:

Available:

- ARM9 routines to start the DSP, load binaries, and basic communications.
- libteak: New library to simplify the development of binaries for the DSP.
- teaktool: Tool that converts ELF files for Teak into TLF (Teak Loadable Format).
- Example of loading a DSP binary and communicating with it.

Left to do:

- ARM9 <-> Teak DMA transfers.
- ARM and Teak IRQ support.
- High level FIFO library.
- Documentation and examples.
- Improve Teak LLVM toolchain.

The LLVM toolchain issue is by far the biggest task here, and the one where I can't help much. I've created a task to track that work: https://github.com/blocksds/sdk/issues/93

**Comment by AntonioND** [comment]
Just an update about the progress on this task. Currently:

- CMD/REPLY registers, semaphores, FIFO transfers and timers are working.
- DMA transfers between ARM9 an DSP are working and tested.
- IRQs are supported (even timer interrupts, which are actually traps).
- Direct DSP output to the speakers using BDTMP is working.
- There are examples of all the mentioned features.

Remaining work:

- Asynchronous DMA transfers.
- Direct microphone input using BDTMP.
- Examples for both features.

**Comment by AntonioND** [comment]
I think we can close this task for now. The only missing task from my last message is the high level FIFO library, but I don't think this is worth the effort right now.
