### ISSUE TITLE
Support `realpath()`

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#72]

**Comment by AntonioND** [comment]
I've implemented it here: https://github.com/blocksds/libnds/commit/9c5e84e9191263a85d9465e7f050c5fef445dfa1

I'm been developing a test suite for it while I implemented the function, but it isn't clean enough. I'll close this issue when the test suite is upstream.

**Comment by AntonioND** [comment]
I'm happy with this test: https://github.com/blocksds/sdk/commit/e497a8c583dc4a772ef9510ecfe4fa4616489e47
