### ISSUE TITLE
`nproc` does not exist on macOS

### ISSUE THREAD

**Issue by lifehackerhansol** [blocksds/sdk#77]
Not much else to say. Everything during `BLOCKSDS=$PWD make install` uses nproc which isn't there.

Is this actually needed? None of the apps are all that big to warrant actually using nproc I think. Stuff like ndstool for example rarely if ever needs to get rebuilt.

I'll think of ways to get around it without breaking makefiles, but it's still something to think about.

**Comment by AntonioND** [comment]
This should fix it: https://github.com/blocksds/sdk/commit/2bf4ca1318134ebf48feff7aa1af9573f646349f
