### ISSUE TITLE
Filesystem NitroFAT speed vs NitroFS

### ISSUE THREAD

**Issue by C3RV1** [blocksds/sdk#81]
While trying to port a project of mine to BlocksDS I ran into an issue while trying to stream music from a NitroFAT file. The speed seems to be about 26x slower than NitroFS from devkitpro, which makes the game lag a lot and consumes most of the CPU.

I don't know how normally you'd perform benchmarking, but I've created a simple test program to test this speed using timers to, well, time the two.

The code is the following (`nitro:/z_audio/mus_ruins.wav` is a 7MB file):
```c++
#include <nds.h>
#include <filesystem.h>
#include <string>
#include <cstdio>

int main() {
    powerOn(POWER_ALL);
    if (!nitroFSInit(nullptr)) {
        nocashMessage("nitroFSInit failure!\n");
        return -1;
    }
    
    char buffer[1024];
    int timeTaken[100]{0};
    FILE *f = fopen("nitro:/z_audio/mus_ruins.wav", "rb");
    for (int & i : timeTaken) {
        timerStart(2, ClockDivider::ClockDivider_64, 0, nullptr);
        for (int j = 0; j < 10; j++) {
            fread(buffer, 1024, 1, f);
        }
        timerPause(2);
        i = timerElapsed(2);
    }

    int sum = 0;
    for (int & i : timeTaken) {
        sum += i / 100;
    }
    std::string res = "Taken, on average, " + std::to_string(sum) + " ticks.";
    nocashMessage(res.c_str());
    while(true) {
        swiWaitForVBlank();
    }
    return 0;
}
```

(in no$gba) BlocksDS's NitroFAT averages 26329 ticks, while NitroFS ([implemented here](https://github.com/C3RV1/UndertaleNDS/blob/main/source/nitrofs.c)) averages 1000 ticks.

**Comment by AntonioND** [comment]
I think this is related to https://github.com/blocksds/sdk/issues/23

**Comment by AntonioND** [comment]
Fixed in https://github.com/blocksds/libnds/pull/41
