### ISSUE TITLE
Transfer region is in cached RAM on DSi

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#82]
https://github.com/blocksds/libnds/blob/ea6f7c9a106d907acbd7c0f32a63bdaf8be388d7/source/arm9/system/mpu_setup.s#L33-L35

On DS:

0x02000000 to 0x02400000: Cached main RAM
0x02400000 to 0x03000000: Uncached main RAM mirrors

On DS debugger:

0x02000000 to 0x02800000: Cached main RAM
0x02800000 to 0x03000000: Uncached main RAM mirror

On DSi and DSi debugger:

0x02000000 to 0x03000000: Cached main RAM
0x0C000000 onwards: Uncached main RAM mirror

On all:

0x02FF0000 to 0x02FF4000: DTCM

0x02FFF000: Transfer Region https://github.com/blocksds/libnds/blob/ea6f7c9a106d907acbd7c0f32a63bdaf8be388d7/source/common/libnds_internal.h#L28

This means that on DSi (and the debugger version of DSi) the transfer region falls in cached RAM. This is a bug, as this region should always be in uncached RAM so that the CPUs see the updates from the other CPUs without flushing or invalidating the cache.

**Comment by AntonioND** [comment]
I guess that the right fix is to make that define return a different address on DSi, but it is likely going to break some code that relies on the define being a define.

**Comment by Lorenzooone** [comment]
Won't the higher priority of the DTCM area fix this?

**Comment by AntonioND** [comment]
Check my message, the range of DTCM doesn't cover that address.

**Comment by Lorenzooone** [comment]
Oh, snap! You are right! I was focused on the DTCM.

**Comment by AntonioND** [comment]
This patch should fix the issue: https://github.com/blocksds/libnds/commit/5715e09207252c5de6ad1f5f9eb52c24739615db

This fix is suboptimal in DSi debugger consoles, but who even has one of them? And it's as suboptimal as the previous location, so the only change of this patch is that now the transfer region isn't cached in DSi mode, which is what the patch tries to achieve.

I've added a test to this repository to check if this breaks in the future: https://github.com/blocksds/sdk/commit/3f38e3c134e126c32f07dfa1b590e84f00ab51ea

**Comment by AntonioND** [comment]
I've created a new issue to keep track of moving the transfer region on DSi debuggers: https://github.com/blocksds/sdk/issues/84
