### ISSUE TITLE
Define a new location for the transfer region in DSi debugger

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#84]
Related to https://github.com/blocksds/sdk/issues/82 and https://github.com/blocksds/sdk/issues/32

A DSi has 16 MB of RAM, and a DSi debugger has 32 MB of RAM.

In DSi mode the transfer region is right before the end of the 16 MB of a regular DSi, which means it's right in the middle of the 32 MB of the debugger model, which isn't ideal. It should be placed at the end of the 32 MB.

Even though almost nobody owns a DSi debugger, it is possible to run DSi games on a 3DS with TWL_FIRM, and it is possible to give 32 MB to the DSi game, so supporting the layout of DSi debugger consoles is useful.

In any case, at the moment, the last 16 MB of DSi RAM of debugger consoles can't be used like normal RAM. The linkerscript doesn't have any definition for them, it also needs to be modified.

**Comment by asiekierka** [comment]
This is infeasible regardless. Memory at `2FFE000` onwards is used to store the DSi header; the memory will thus remain non-contiguous.

I recommend closing this issue and moving towards something more akin to "treating the extra 16 MB of RAM like Slot-2 external memory". It's a rare scenario anyway (DSi mode on 3DS and maybe in-emulator development, in practice - we don't really target IS-TWL users).

**Comment by AntonioND** [comment]
Makes sense: https://github.com/blocksds/sdk/issues/100
