### ISSUE TITLE
Implement st.st_ino the libfat way

### ISSUE THREAD

**Issue by lifehackerhansol** [blocksds/sdk#85]
Currently FatFs sets st_ino to zero (which technically is the correct behaviour, since FAT does not have inodes). This breaks a handful of both old and new source code (notably, [nds-hb-menu](https://github.com/devkitPro/nds-hb-menu)) which expects st_ino to be the address of the file's first cluster.

[libslim](https://github.com/DS-Homebrew/libslim), another NDS FatFs implementation, handles it this way: https://github.com/DS-Homebrew/libslim/blob/1a144ff91d740c3dfcdb08feaa91b03a725b7f6c/libslim/source/elm.c#L352

**Comment by AntonioND** [comment]
I guess that the approach of libslim is fine. Feel free to create a PR if you want. If not, I'll get around doing it when I have a bit of time.

**Comment by AntonioND** [comment]
Ah, wait, I hadn't seen that this relies on an unofficial patch to FatFs https://github.com/DS-Homebrew/libslim/blob/1a144ff91d740c3dfcdb08feaa91b03a725b7f6c/libslim/source/ff.c#L2818-L2829

I'm not so sure anymore...

**Comment by asiekierka** [comment]
In my opinion, this constitutes a breach of the abstraction layer between the C filesystem abstraction and FAT, but I wouldn't consider it particularly harmful. BlocksDS already has two non-standard patches to FatFs.

Of course, this would have to be well-documented.

**Comment by asiekierka** [comment]
>which technically is the correct behaviour, since FAT does not have inodes

Technically, the correct behaviour is for the combination of `st_dev` and `st_ino` to be unique for each file. The starting cluster is a fairly good approximation of that, though it doesn't work for zero-byte files, which don't have any cluster allocated.

There's an `ld_clust` function in FatFS which can be easily adapter to pull out the starting cluster information.
