### ISSUE TITLE
Support RTC in emulators

### ISSUE THREAD

**Issue by AntonioND** [blocksds/sdk#87]
Currently RTC support in libnds relies on the RTC interrupt. Unfortunately, this interrupt isn't supported in most emulators. Only no$gba supports it, as far as I know.

Of course, the implementation of libnds also works on hardware, but major emulators like melonDS and DeSmuME don't, so it's worth thinking about supporting emulators in a different way. Ideally, they would implement the RTC interrupt, but it doesn't look like this is going to happen anytime soon.

Maybe we could update the RTC value every frame. After all, the one that updates it is the ARM7 CPU.

I'm flagging this as a bug, but it could also be considered an enhancement.

**Comment by AntonioND** [comment]
Now it's possible to change the way the ARM7 sets up the RTC update routine and use a timer instead of the RTC interrupt. https://github.com/blocksds/libnds/commit/3b44f0947e6712b959e46c7d9c29aabd629e53f1

**Comment by asiekierka** [comment]
Let it be known that I don't really agree with this decision; libnds should not be making concessions for emulator bugs. It's a bad precedent to set.

**Comment by profi200** [comment]
I'm not sure if it was this one but if i recall correctly RTC interrupts are also broken on 3DS in DS(i) mode. I'm not even sure if the hardware actually supports this or if this is just a bug in TwlBg.

**Comment by AntonioND** [comment]
> Let it be known that I don't really agree with this decision; libnds should not be making concessions for emulator bugs. It's a bad precedent to set.

I agree that in general it's a bad idea to do this, but there is only one emulator that I know of that supports this feature: no$gba. Even if melonDS and DeSmuME suddenly supported it tomorrow it would take ages for the fix to reach every user. In the meantime, every user of the RTC functions would assume that the library is buggy, and complain to me, or worse, complain somewhere where I can't see it to explain why it happens.

And that's the actually bad thing. I can explain why it doesn't work, but that doesn't solve any problem if the emulators don't support it and this is a low priority bug for them.

Having a pure library that doesn't work is a bit useless.

**Comment by brais-sg** [comment]
> I'm not sure if it was this one but if i recall correctly RTC interrupts are also broken on 3DS in DS(i) mode. I'm not even sure if the hardware actually supports this or if this is just a bug in TwlBg.

I remember this back in the days of MicroLua DS. On 3DS (Booting from a DSTWO flashcard), the RTC only updated if I pressed the home button.
Since that day I always used a timer to keep track of the time, seems that the RTC interrupt is also broken on 3DS in TWL/NTR mode.

**Comment by AntonioND** [comment]
As far as I understand, a lot of the peripherals of DS are emulated in the 3DS, so it's possible that they decided that adding support for the RTC interrupt was a waste of time, given that official games don't use it.

**Comment by AntonioND** [comment]
Huh, interesting discussion here as well: https://github.com/TASEmulators/desmume/issues/280#issuecomment-497974236

**Comment by AntonioND** [comment]
Actually, the more I think about this issue, the more I realize that emulators are going to have trouble with it no matter what. What about speedup modes? Do we increase the speed of the RTC, or do we still take the date from the OS?

@zeromus sorry to bother you, but did you ever suggest a specific change to libnds that would play nice with emulators?

**Comment by asiekierka** [comment]
If the 3DS is among devices not supporting RTC interrupts correctly, then I retract my statement - libnds should support the DS(i) mode of the 3DS correctly.

As an alternative option, wouldn't only polling the RTC when `time()` is called - perhaps with a small cache and invalidation on VBlank, to avoid polling it too often - be among the most appropriate options?

**Comment by AntonioND** [comment]
But wouldn't some games call ``time()`` every frame anyway? I should really test how long it takes to read the RTC on hardware, I only tested it on melonDS, but it was certainly a lot of time.

**Comment by AntonioND** [comment]
By the way, I don't have a 3DS with TWL_FIRM or whatever is needed to run DSi games. Could someone try the combined template in theirs just to check? It displays the date on the bottom screen and it used the RTC interrupt.

**Comment by profi200** [comment]
If someone makes me a build i will test it on 3DS. I don't have the toolchain and all set up to compile this.

**Comment by AntonioND** [comment]
> If someone makes me a build i will test it on 3DS. I don't have the toolchain and all set up to compile this.

There you go, thanks!

[template_combined.nds.zip](https://github.com/blocksds/sdk/files/12904619/template_combined.nds.zip)

**Comment by profi200** [comment]
Can confirm. The time is stuck at the initial reading and doesn't advance at all. Tested via a flashcard in DS mode.

**Comment by AntonioND** [comment]
Oh, so 3DS in DS mode doesn't support it? That's even worse, I can test that too, I thought it was only a problem in DSi mode because that was the comment.

**Comment by profi200** [comment]
It's both. That's why i used "DS(i)" to mean both.

**Comment by brais-sg** [comment]
Just some more info about this, seems that the RTC emulation does in fact advance the clock, is just the RTC interrupt that is not emulated. You can test it on the 3DS closing the screen and opening it again, which triggers a clock resync.

The HOME button also triggers a lid close event, so the clock will sync when pressed.
So, is reading the RTC every ~30 frames an option, for example? Or does it really need to use a timer on the ARM7 side to trigger the counting irq every second?

**Comment by asiekierka** [comment]
> But wouldn't some games call `time()` every frame anyway?

My opinion is that then they can cache it themselves; is there a good reason to do that in a performance-sensitive context?

**Comment by AntonioND** [comment]
I've just tested on real hardware, the ``resyncClock()`` function takes more than 7% of the CPU time during a frame. It can't be called on demand, it would be too disruptive for games that use the ARM7 intensively and don't know about this issue.

Realistically, I think that the hardware timer is the only solution, even if it causes a drift over really long periods of gameplay.

[rtc_cpu_time.zip](https://github.com/blocksds/sdk/files/12905200/rtc_cpu_time.zip)

**Comment by profi200** [comment]
For the record, i looked it up and the hardware does support the IRQ. See bottom of the page: https://problemkaputt.de/gbatek-3ds-gpio-registers.htm

**Comment by AntonioND** [comment]
If the official ARM11 code that runs in DS mode doesn't take care of it, it doesn't really matter, right? We can't ask users to use a modified firmware just to have RTC support.

**Comment by AntonioND** [comment]
Well, for the time being I'm going to switch all ARM7 cores in the examples of BlocksDS to using a timer interrupt.

Of course, I won't remove the code that sets up the RTC interrupt so that old programs don't stop building, but I'm going to document that it doesn't work in a 3DS, and it shouldn't be used. I guess I'll mark it as deprecated.

**Comment by profi200** [comment]
Yeah, and none of the reimplementations which could fix it are out yet.

**Comment by zeromus** [comment]
My suggestion was always for libnds to stop using the IRQ. can't it just do whatever all the retail games do?

**Comment by AntonioND** [comment]
Yes, I've already added the functionality to do that. I'll completely switch to that in all the examples tonight.

**Comment by AntonioND** [comment]
Commit that deprecates the RTC interrupt function in libnds: https://github.com/blocksds/libnds/commit/f6dd49cd94a8343ac2dd1867d1f2779baaf13656

It also updates all the ARM7 examples in this repository to use the new function based on hardware timers. https://github.com/blocksds/sdk/commit/48247dd58661d3cc63a2722aa8235bfca6d79f84

**Comment by AntonioND** [comment]
I'm switching this into an enhancement because the bug part of the task is now fixed.

**Comment by AntonioND** [comment]
I'm not sure if there is anything left to do here. Reading the RTC is quite slow, so I still think that reading it on demand will likely have side effects in games that push the ARM7 to the limit. The current strategy of using a timer to update the time every second works pretty well, and reading the RTC chip after leaving sleep mode doesn't have any negative side effect.

Is there any reason why we should change this code, or can we close this issue?

**Comment by AntonioND** [comment]
I'm going to close this issue. If anyone has suggestions in the future, feel free to open a new issue.
