### ISSUE TITLE
Remove NitroFAT

### ISSUE THREAD

**Issue by asiekierka** [blocksds/sdk#88]
NitroFAT was a way to avoid writing a new NitroFS implementation and thus simplify the amount of logic that goes into the libc wrappers. However, the performance penalty that comes from accessing two FAT file systems over a simpler file system is noticeable.

As such, it's time to replace NitroFAT with a new NitroFS implementation. This will be a fair bit of work, but will fix https://github.com/blocksds/sdk/issues/81 .  Also a good idea to fix https://github.com/blocksds/sdk/issues/66 while at it.

**Comment by AntonioND** [comment]
Fixed in https://github.com/blocksds/libnds/pull/41
