### ISSUE TITLE
Examples makefiles are bugged

### ISSUE THREAD

**Issue by Constancies** [blocksds/sdk#96]
The `Makefile` for `examples` currently searches for `$(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile`, however, the `default_makefiles` directory does not exist in the toolchain (tested with both the wonderful distribution and Docker container).

**Comment by AntonioND** [comment]
Are you using the examples from the current master branch, while using the version 0.9.1 SDK? That won't work, you need to checkout the v0.9.1 tag to use the examples. There have been several changes to the makefile since then.

**Comment by Constancies** [comment]
Ah, that is likely what's happening. Thank you

**Comment by AntonioND** [comment]
No problem! I'll close this issue, but feel free to reopen it if checking out the right tag didn't fix your problem.
