### ISSUE TITLE
Fork r4denc

### ISSUE THREAD

**Issue by lifehackerhansol** [blocksds/sdk#97]
r4denc is here: https://github.com/devkitPro/dstools/tree/master/src/r4denc

It would be nice to see this forked, as it is a very useful tool for the original R4 and other carts that use the same encryption scheme for their boot file. r4denc is something I'd consider feature complete, so I doubt it'll see any updates even on upstream side.

**Comment by lifehackerhansol** [comment]
asie said no

**Comment by AntonioND** [comment]
I agree that having tools to build flashcard-specific binaries is out of scope for the SDK.
